package display;

public enum ControlFuncTest {
	PLAYPAUSE, STOP, START, FAST, SLOW, SKIP1C, SKIP1G, SKIP10G, SHOWBEST, SHOWMID, SHOWWORST, GENERATEPOP, SPEED1X, TOGGLEVIEW, RESETVIEW, TEST_ONE_BY_ONE
}
